### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by ihovsky** [PheeZz/XTLS-Reality-bot#7]
А как запустить обновление бота?

**Comment by PheeZz** [comment]
Если проект был установлен ранее и есть желание обновиться до последнего коммита - последовательно используйте следующие команды
```bash
cd XTLS-Reality-bot
git pull
systemctl restart xtls-reality-bot.service
```

**Comment by ihovsky** [comment]
> Если проект был установлен ранее и есть желание обновиться до последнего коммита - последовательно используйте следующие команды
> 
> ```shell
> cd XTLS-Reality-bot
> git pull
> systemctl restart xtls-reality-bot.service
> ```

А настройки не слетят?

**Comment by PheeZz** [comment]
> > Если проект был установлен ранее и есть желание обновиться до последнего коммита - последовательно используйте следующие команды
> 
> > 
> 
> > ```shell
> 
> > cd XTLS-Reality-bot
> 
> > git pull
> 
> > systemctl restart xtls-reality-bot.service
> 
> > ```
> 
> 
> 
> А настройки не слетят? 

Не слетят, обновление таким образом не затрагивает конфигурационные файлы

**Comment by ihovsky** [comment]
Обновился, но конструктор рассылки пользователям не появился..

**Comment by ihovsky** [comment]
> > > Если проект был установлен ранее и есть желание обновиться до последнего коммита - последовательно используйте следующие команды
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > cd XTLS-Reality-bot
> > 
> > 
> > > git pull
> > 
> > 
> > > systemctl restart xtls-reality-bot.service
> > 
> > 
> > > 
> > 
> > 
> > А настройки не слетят?
> 
> Не слетят, обновление таким образом не затрагивает конфигурационные файлы

Обновился, но конструктор рассылки пользователям не появился..

**Comment by PheeZz** [comment]
Пожалуйста, выполните следующие команды еще раз и пришлите трейсбек (вывод терминала/stdout) по каждой команде.
Если вы вносили какие-либо локальные изменения - при попытке ввода `git pull` вы увидите ошибку с предложением "спрятать локальные изменения". В таком случае перед выполнением команды `git pull` выполните `git stash`.
```bash
cd XTLS-Reality-bot
git pull
systemctl restart xtls-reality-bot.service
systemctl status xtls-reality-bot.service
```

Для вставки трейсбека оберните вывод в тройные апострофы для удобочитаемости:
\```bash
traceback here
\```

**Comment by ihovsky** [comment]
> Пожалуйста, выполните следующие команды еще раз и пришлите трейсбек (вывод терминала/stdout) по каждой команде. Если вы вносили какие-либо локальные изменения - при попытке ввода `git pull` вы увидите ошибку с предложением "спрятать локальные изменения". В таком случае перед выполнением команды `git pull` выполните `git stash`.
> 
> ```shell
> cd XTLS-Reality-bot
> git pull
> systemctl restart xtls-reality-bot.service
> systemctl status xtls-reality-bot.service
> ```
> 
> Для вставки трейсбека оберните вывод в тройные апострофы для удобочитаемости: ```bash traceback here ```

После ввода git pull:
```bash
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

Последовал вашему совету с git stash и все заработало. Прошу прощения за свою глупые вопросы :)
