### ISSUE TITLE
А есть возможность подключить этого бота на 2 сервера)?

### ISSUE THREAD

**Issue by rasulovdd** [PheeZz/XTLS-Reality-bot#8]
Здравствуйте, подскажите пожалуйста, а планируется ли написать функционал управления несколькими серверами?
чтобы например у пользователя был выбор локации

**Comment by PheeZz** [comment]
Здравствуйте, на данный момент такого функционала нет, в ближайшее время реализация не планируется.

**Comment by rasulovdd** [comment]
спасибо
